### PR TITLE
Changed ID type as int to GUID.

### PR DESCRIPTION
**Pull request by larshg**
Updated to SQLite 1.0.99.0

### CODE REVIEW

**Comment by larshg** [comment]
I still need to properly rework the AD backend - but you can try out the standard with internal db?

**Comment by larshg** [comment]
I just did a rebase - to avoid getting the highlight from bower etc.

**Comment by larshg** [comment]
I have some trouble getting to save the GUID as a string the SQLite db - I got it working one day, but right now it fails and saves it as a binary... but the it fails when you query against a ID... So its not optimal atm...

**Comment by larshg** [comment]
Found out I had removed this part `BinaryGUID=False;` from the connection string.

**Comment by RedX2501** [comment]
Why the sqlitedb Update?

In general i think the change from Int to Guid is a good idea.

**Comment by RedX2501** [comment]
Thanks I've merged this by rebasing your latest three commits as I was having merging conflicts.

**Pull request closed without merging**
